// Generate projects/README.md from projects/registry.json.
//
//   node projects/render-index.mjs           write it
//   node projects/verify-registry.mjs        exit 1 if it has fallen behind
//
// The index is generated rather than maintained because a hand-kept table of
// twenty statuses is twenty claims that can quietly stop being true. Editing the
// generated file is caught by the verifier, not by anyone remembering.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));

const LABEL = {
  planned: "未開始",
  in_progress: "進行中",
  closed: "已結案",
};

export function renderIndex(registry) {
  const lines = [];
  lines.push("<!-- GENERATED by projects/render-index.mjs from projects/registry.json.");
  lines.push("     Do not edit: projects/verify-registry.mjs compares this file to the registry");
  lines.push("     and exits 1 when they disagree. -->");
  lines.push("# 二十個專案");
  lines.push("");
  lines.push("每一個專案未來都有自己的介紹頁。這份索引由 `registry.json` 產生，");
  lines.push("而登記表裡的每一句話都由 `verify-registry.mjs` 對著這個 repo 查證過——");
  lines.push("一個專案不能宣稱自己結案而它的 commit 不在這裡。");
  lines.push("");

  const closed = registry.projects.filter((p) => p.status === "closed").length;
  const active = registry.projects.filter((p) => p.status === "in_progress").length;
  lines.push(`**${closed} 已結案 · ${active} 進行中 · ${20 - closed - active} 未開始**`);
  lines.push("");
  lines.push("| # | 專案 | 狀態 | 一句話 | 介紹頁 |");
  lines.push("|---:|---|---|---|---|");
  for (const p of registry.projects) {
    const name = p.title_zh === null ? "—" : `**${p.title_zh}**`;
    const summary = p.summary_zh === null ? "—" : p.summary_zh;
    const page = p.intro_page === null ? "未建立" : `[頁面](${p.intro_page})`;
    lines.push(`| ${p.id} | ${name} | ${LABEL[p.status]} | ${summary} | ${page} |`);
  }
  lines.push("");

  for (const p of registry.projects) {
    if (p.status === "planned") continue;
    lines.push(`## ${p.id}. ${p.title_zh}`);
    lines.push("");
    lines.push(`\`${p.slug}\` · ${LABEL[p.status]}`);
    lines.push("");
    if (p.summary_zh !== null) { lines.push(p.summary_zh); lines.push(""); }
    if (p.demonstrates.length > 0) {
      lines.push("**這個專案量出來的東西：**");
      lines.push("");
      for (const item of p.demonstrates) lines.push(`- ${item}`);
      lines.push("");
    }
    if (p.measured !== null) {
      lines.push("```text");
      const m = p.measured;
      lines.push(`測試              ${m.tests} / ${m.tests - m.test_failures} 通過`);
      lines.push(`鑽孔              ${m.drills} 支，${m.drill_mutations_surviving} 個變異活下來`);
      lines.push(`驗收 ID           ${m.acceptance_ids} 條，${m.acceptance_ids_open} 條未結`);
      lines.push(`外包進樹的單元    ${m.outsourced_units_in_tree} 個`
        + `${m.outsourced_units_byte_identical ? "，逐位元未改" : ""}`);
      lines.push("```");
      lines.push("");
    }
    if (p.closed_commit !== null) {
      lines.push("```text");
      lines.push(`commit  ${p.closed_commit}`);
      lines.push(`tree    ${p.closed_tree}`);
      lines.push(`結案    ${p.closed_date}`);
      lines.push("```");
      lines.push("");
    }
    if (p.seats !== null) {
      lines.push(`席位：建置 ${p.seats.build} · manifest/oracle ${p.seats.manifest_and_oracle}`
        + ` · 系統驗收 ${p.seats.system_acceptance}`);
      lines.push("");
    }
  }
  return lines.join("\n");
}

if (import.meta.url === `file://${process.argv[1].replace(/\\/g, "/")}`
    || process.argv[1].endsWith("render-index.mjs")) {
  const registry = JSON.parse(readFileSync(path.join(here, "registry.json"), "utf8"));
  const out = path.join(here, "README.md");
  writeFileSync(out, renderIndex(registry), "utf8");
  process.stdout.write(`  wrote projects/README.md\n`);
}
