import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));

export function renderReadme(d) {
  const lines = [];
  lines.push("<!-- GENERATED by render-readme.mjs. Do not edit directly. -->");
  lines.push("# App 2 preregistration — file-manager-basic");
  lines.push("");
  lines.push(`Schema \`${d.schema}\` · revision \`${d.revision}\` · position \`${d.position}\``);
  lines.push("");
  lines.push("> CANDIDATE PREREGISTRATION. It defines what later work must prove; it does not authorize product code, provider calls, merge, release or deployment.");
  lines.push("");
  lines.push("## Product boundary");
  lines.push("");
  lines.push(d.product_claim);
  lines.push("");
  lines.push("One selected root is always visible; changing it is explicit; navigation above it is refused. Remembered-root persistence is not required.");
  lines.push("");
  lines.push("## Active denominator");
  lines.push("");
  lines.push("| Capability | Acceptance rows |");
  lines.push("|---|---:|");
  for (const capability of d.active_denominator) {
    lines.push(`| \`${capability}\` | ${d.capability_acceptance_map[capability].length} |`);
  }
  lines.push("");
  lines.push(`Total: **${d.active_denominator.length} capabilities / ${Object.keys(d.acceptance_rows).length} independently named rows**.`);
  lines.push("");
  lines.push("Path authority, snapshot identity, result unions and error projection are cross-cutting contracts, not extra denominator items.");
  lines.push("");
  lines.push("## Primary GUI workflow");
  lines.push("");
  for (const step of d.primary_workflow) lines.push(`1. **${step.id}** — ${step.action}`);
  lines.push("");
  lines.push("## Result and snapshot contract");
  lines.push("");
  lines.push(`Overall: \`${d.cross_cutting_contracts.operation_result.overall_statuses.join(" | ")}\`.`);
  lines.push(`Per entry: \`${d.cross_cutting_contracts.operation_result.per_entry_statuses.join(" | ")}\`.`);
  lines.push("");
  lines.push("Generation has one meaning only: it identifies the published snapshot sequence. Every published snapshot increments it exactly once, whether publication follows refresh or mutation. Mutation truth comes from per-entry outcomes.");
  lines.push("");
  lines.push(`Snapshot result states: \`${d.cross_cutting_contracts.snapshot.result_states.join(" | ")}\`. The unavailable arm carries no fabricated snapshot and requires a typed observation code.`);
  lines.push("");
  lines.push("## V0 reparse and path boundary");
  lines.push("");
  lines.push("Reparse entries may be displayed, but a reparse root, traversal through a reparse entry and mutation through one are refused. Resolved-string containment is not claimed as race-safe confinement.");
  lines.push("");
  lines.push("## Deferred and excluded");
  lines.push("");
  for (const item of d.deferred_capabilities) lines.push(`- **Deferred \`${item.id}\`:** ${item.rationale}`);
  for (const item of d.excluded_scope) lines.push(`- Excluded: ${item}`);
  lines.push("");
  lines.push("## Fixtures and action shape");
  lines.push("");
  const files = d.fixture_contract.entries.filter((x) => x.kind === "file");
  const directories = d.fixture_contract.entries.filter((x) => x.kind === "directory");
  const bytes = files.reduce((sum, x) => sum + x.bytes, 0);
  lines.push(`${directories.length} pinned directories, ${files.length} pinned files, ${bytes} payload bytes. Payload hex and SHA-256 are owned by independent acceptance, not derived by the product.`);
  lines.push("");
  lines.push("Every dynamic subject must prove its precondition before action. An unproved precondition is `DID_NOT_APPLY` and an acceptance failure; it never counts as a caught attack.");
  lines.push("");
  for (const action of d.timing_policy.bounded_actions) {
    lines.push(`- \`${action.id}\`: ${action.trigger}; subject ${action.subject}; stop when ${action.timer_stop}.`);
  }
  lines.push("");
  lines.push("The caps are hang detectors, not performance claims. Replacing a GUI batch command with a test-side loop changes the subject and fails acceptance.");
  lines.push("");
  lines.push("Every cap breach is classified as `product_hang`, `instrument_subject_mismatch` or `environment_limit`. Only a proven product hang fails the product; harness mismatch invalidates the harness and environment limits remain `NotMeasured`.");
  lines.push("");
  lines.push("## Comparator");
  lines.push("");
  lines.push(`Mode: \`${d.comparator.mode}\`. ${d.comparator.scope}. Causal claim allowed: \`${d.comparator.causal_claim_allowed}\`.`);
  lines.push("");
  lines.push("## Roles for this preregistration");
  lines.push("");
  lines.push(`- Draft: ${d.membership.preregistration_author}`);
  lines.push(`- First independent attack: ${d.membership.first_independent_attacker}`);
  lines.push(`- Denominator/acceptance attack: ${d.membership.denominator_and_acceptance_attacker}`);
  lines.push("");
  lines.push("## Stop boundary");
  lines.push("");
  lines.push(d.stop_boundary);
  lines.push("");
  return lines.join("\n");
}

if (process.argv[1] !== undefined && process.argv[1].endsWith("render-readme.mjs")) {
  const check = process.argv.includes("--check");
  const rootIndex = process.argv.indexOf("--root");
  const root = rootIndex >= 0 ? path.resolve(process.argv[rootIndex + 1]) : here;
  const prereg = JSON.parse(fs.readFileSync(path.join(root, "preregistration.json"), "utf8"));
  const wanted = renderReadme(prereg);
  const file = path.join(root, "README.md");
  const found = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
  if (check) {
    if (found !== wanted) {
      process.stderr.write("README.md is stale or missing; run render-readme.mjs\n");
      process.exit(1);
    }
    process.stdout.write("README.md is current\n");
  } else {
    fs.writeFileSync(file, wanted, "utf8");
    process.stdout.write("wrote README.md\n");
  }
}
