// Generate portfolio/index.json and portfolio/README.md.
//
//   node portfolio/render-index.mjs            write both
//   node portfolio/verify-portfolio.mjs        exit 1 if either has fallen behind
//
// Two inputs, and they own different things. `roadmap.json` owns identity: which
// slug sits at which of the twenty fixed positions, and where that was decided.
// `products/NN-slug.json` owns work, and only exists once there is work.
//
// The index stores no lifecycle fact of its own. current_gate, the projection
// and technical_close_eligible are computed at render time from the stage
// records, so there is nothing here that can quietly stop matching them.
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { currentGate, projection, technicalCloseEligible } from "./lifecycle.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const PRODUCTS = path.join(here, "products");

const LABEL = {
  not_started: "未開始",
  active: "進行中",
  blocked: "阻塞",
  technical_closed: "技術結案",
};

export function loadRoadmap() {
  return JSON.parse(readFileSync(path.join(here, "roadmap.json"), "utf8"));
}

/** Product records, keyed by the padded position they declare. */
export function loadRecords() {
  if (!existsSync(PRODUCTS)) return new Map();
  const records = new Map();
  for (const name of readdirSync(PRODUCTS).sort()) {
    if (!name.endsWith(".json")) continue;
    const record = JSON.parse(readFileSync(path.join(PRODUCTS, name), "utf8"));
    records.set(record.position, { record, file: `portfolio/products/${name}` });
  }
  return records;
}

export function buildIndex(roadmap, records) {
  const positions = roadmap.positions.map((entry) => {
    const held = records.get(entry.position);
    if (held === undefined) {
      // No record means no work, and the index says exactly that. A placeholder
      // carrying default fields would be a claim about work nobody has done.
      return {
        position: entry.position,
        slug: entry.slug,
        selection: entry.selection,
        record: null,
      };
    }
    const { record, file } = held;
    return {
      position: entry.position,
      slug: entry.slug,
      selection: entry.selection,
      record: file,
      title_zh: record.title_zh,
      title_en: record.title_en,
      derived: {
        current_gate: currentGate(record),
        lifecycle: projection(record),
        technical_close_eligible: technicalCloseEligible(record),
      },
      close: record.close ?? null,
      intro_page: record.intro_page ?? null,
    };
  });
  return {
    schema: "mssp.portfolio-index/v0-experimental",
    note: "GENERATED by portfolio/render-index.mjs from roadmap.json and products/*.json. Every field under `derived` is computed from that product's stage records and stored nowhere. Do not edit: portfolio/verify-portfolio.mjs exits 1 when this file and its inputs disagree.",
    canonical_ref: "main",
    portfolio_size: 20,
    positions,
  };
}

export function renderReadme(index, records) {
  const lines = [];
  lines.push("<!-- GENERATED by portfolio/render-index.mjs. Do not edit:");
  lines.push("     portfolio/verify-portfolio.mjs exits 1 when this disagrees with its inputs. -->");
  lines.push("# 二十個應用專案");
  lines.push("");
  lines.push("固定二十個位置。**身分**在 `roadmap.json`，**工作**在 `products/NN-slug.json`，");
  lines.push("而後者只有在真的有工作之後才存在——一個帶著預設欄位的佔位符，");
  lines.push("是一份關於沒人做過的工作的宣稱。");
  lines.push("");
  lines.push("`current_gate`、生命週期投影與 `technical_close_eligible` 都是從 stage 紀錄**推導**的，");
  lines.push("沒有存在任何地方。一份存下來的摘要會跟它摘要的東西不一致，而那時被讀的是摘要。");
  lines.push("");
  lines.push("結案的 commit 必須從 `main` **可達**，而且記錄的 tree 必須等於那個 commit 的 tree。");
  lines.push("物件存在不算數：一個 fetch 下來但沒合併的 commit 也存在，而它什麼都沒證明。");
  lines.push("");

  const withRecord = index.positions.filter((p) => p.record !== null);
  const closed = withRecord.filter((p) => p.derived.lifecycle === "technical_closed").length;
  const named = index.positions.filter((p) => p.slug !== null).length;
  lines.push(`**${closed} 技術結案 · ${withRecord.length - closed} 進行中 · `
    + `${named - withRecord.length} 已命名未開始 · ${20 - named} 待審定名**`);
  lines.push("");
  lines.push("| # | 專案 | 生命週期 | 目前的關卡 | 介紹頁 |");
  lines.push("|---:|---|---|---|---|");
  for (const p of index.positions) {
    if (p.slug === null) {
      lines.push(`| ${p.position} | *待審定名* | — | — | — |`);
      continue;
    }
    if (p.record === null) {
      lines.push(`| ${p.position} | \`${p.slug}\` | 未開始 | — | — |`);
      continue;
    }
    const gate = p.derived.current_gate === null ? "（無）" : `\`${p.derived.current_gate}\``;
    const page = p.intro_page === null ? "未建立" : `[頁面](${p.intro_page})`;
    lines.push(`| ${p.position} | **${p.title_zh}** | ${LABEL[p.derived.lifecycle]} | ${gate} | ${page} |`);
  }
  lines.push("");

  for (const p of index.positions) {
    if (p.record === null) continue;
    const { record } = records.get(p.position);
    lines.push(`## ${p.position}. ${record.title_zh}`);
    lines.push("");
    lines.push(`\`${record.slug}\` · ${LABEL[p.derived.lifecycle]} · 紀錄 \`${p.record}\``);
    lines.push("");
    lines.push(record.summary_zh);
    lines.push("");
    lines.push("| 階段 | 適用性 | 狀態 |");
    lines.push("|---|---|---|");
    for (const stage of record.stages) {
      lines.push(`| \`${stage.stage}\` | ${stage.applicability} | ${stage.state} |`);
    }
    lines.push("");
    if (record.work_items.length > 0) {
      lines.push("**實際做過的工作項目**（變動長度，不是固定格）：");
      lines.push("");
      for (const item of record.work_items) {
        lines.push(`- \`${item.key}\` ${item.title} — ${item.state}`);
      }
      lines.push("");
    }
    if (record.demonstrates.length > 0) {
      lines.push("**這個產品量出來的東西：**");
      lines.push("");
      for (const item of record.demonstrates) lines.push(`- ${item}`);
      lines.push("");
    }
    if (record.measured !== null && record.measured !== undefined) {
      const m = record.measured;
      lines.push("```text");
      lines.push(`測試              ${m.tests} 條，${m.test_failures} 條失敗`);
      lines.push(`鑽孔              ${m.drills} 支，${m.drill_mutations_surviving} 個變異活下來`);
      lines.push(`驗收 ID           ${m.acceptance_ids} 條，${m.acceptance_ids_open} 條未結`);
      lines.push(`外包進樹的單元    ${m.outsourced_units_in_tree} 個`
        + `${m.outsourced_units_byte_identical ? "，逐位元未改" : ""}`);
      lines.push("```");
      lines.push("");
    }
    if (p.close !== null) {
      lines.push("```text");
      lines.push(`commit  ${p.close.commit}`);
      lines.push(`tree    ${p.close.tree}`);
      lines.push(`結案    ${p.close.date}`);
      lines.push("```");
      lines.push("");
    }
    lines.push(`席位：建置 ${record.owners.build} · manifest/oracle `
      + `${record.owners.manifest_and_oracle} · 系統驗收 ${record.owners.system_acceptance}`);
    lines.push("");
  }
  return lines.join("\n");
}

if (process.argv[1] !== undefined && process.argv[1].endsWith("render-index.mjs")) {
  const roadmap = loadRoadmap();
  const records = loadRecords();
  const index = buildIndex(roadmap, records);
  writeFileSync(path.join(here, "index.json"), JSON.stringify(index, null, 2) + "\n", "utf8");
  writeFileSync(path.join(here, "README.md"), renderReadme(index, records), "utf8");
  process.stdout.write("  wrote portfolio/index.json and portfolio/README.md\n");
}
