// Generate portfolio/index.json and portfolio/README.md from the product records.
//
//   node portfolio/render-index.mjs            write both
//   node portfolio/verify-portfolio.mjs        exit 1 if either has fallen behind
//
// The index owns product identity and position, the record reference, the
// DERIVED gate and projection, and the exact close reference. It stores no
// lifecycle fact of its own: everything it shows is computed from the product
// records at render time, so there is nothing here that can quietly stop
// matching them.
//
// The twenty positions are fixed. Nineteen of them have no record and the index
// says exactly that, rather than holding an empty product with default fields —
// a placeholder carrying defaults is a claim about work nobody has done.
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { currentGate, projection, technicalCloseEligible } from "./lifecycle.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const PRODUCTS = path.join(here, "products");
const PORTFOLIO_SIZE = 20;

const LABEL = {
  not_started: "未開始",
  active: "進行中",
  blocked: "阻塞",
  technical_closed: "技術結案",
};

export function loadRecords() {
  if (!existsSync(PRODUCTS)) return new Map();
  const records = new Map();
  for (const name of readdirSync(PRODUCTS).sort()) {
    if (!name.endsWith(".json")) continue;
    const record = JSON.parse(readFileSync(path.join(PRODUCTS, name), "utf8"));
    records.set(record.id, { record, file: `portfolio/products/${name}` });
  }
  return records;
}

export function buildIndex(records) {
  const positions = [];
  for (let id = 1; id <= PORTFOLIO_SIZE; id += 1) {
    const entry = records.get(id);
    if (entry === undefined) {
      positions.push({ id, record: null });
      continue;
    }
    const { record, file } = entry;
    positions.push({
      id,
      slug: record.slug,
      title_zh: record.title_zh,
      title_en: record.title_en,
      record: file,
      derived: {
        current_gate: currentGate(record),
        lifecycle: projection(record),
        technical_close_eligible: technicalCloseEligible(record),
      },
      close: record.close ?? null,
      intro_page: record.intro_page ?? null,
    });
  }
  return {
    schema: "mssp.portfolio-index/v0",
    note: "GENERATED by portfolio/render-index.mjs from portfolio/products/*.json. Every field under `derived` is computed from the product's stage records; none of it is stored there. Do not edit: portfolio/verify-portfolio.mjs exits 1 when this file and the records disagree.",
    portfolio_size: PORTFOLIO_SIZE,
    positions,
  };
}

export function renderReadme(index, records) {
  const lines = [];
  lines.push("<!-- GENERATED by portfolio/render-index.mjs. Do not edit:");
  lines.push("     portfolio/verify-portfolio.mjs exits 1 when this disagrees with the records. -->");
  lines.push("# 二十個應用專案");
  lines.push("");
  lines.push("固定二十個位置。每一個產品的工作項目是**變動長度**的實際紀錄，不是一格二十欄的表格——");
  lines.push("十九個位置目前沒有紀錄，而索引就這樣寫，不放預設值。一個帶著預設值的佔位符，");
  lines.push("是一份關於沒人做過的工作的宣稱。");
  lines.push("");
  lines.push("`current_gate`、生命週期投影與 `technical_close_eligible` 都是從 stage 紀錄**推導**的，");
  lines.push("沒有存在任何地方。一份存下來的摘要會跟它摘要的東西不一致，而那時被讀的是摘要。");
  lines.push("");

  const filled = index.positions.filter((p) => p.record !== null);
  const closed = filled.filter((p) => p.derived.lifecycle === "technical_closed").length;
  lines.push(`**${closed} 技術結案 · ${filled.length - closed} 進行中 · ${20 - filled.length} 尚未建立紀錄**`);
  lines.push("");
  lines.push("| # | 專案 | 生命週期 | 目前的關卡 | 介紹頁 |");
  lines.push("|---:|---|---|---|---|");
  for (const p of index.positions) {
    if (p.record === null) {
      lines.push(`| ${p.id} | — | — | — | — |`);
      continue;
    }
    const gate = p.derived.current_gate === null ? "（無）" : `\`${p.derived.current_gate}\``;
    const page = p.intro_page === null ? "未建立" : `[頁面](${p.intro_page})`;
    lines.push(`| ${p.id} | **${p.title_zh}** | ${LABEL[p.derived.lifecycle]} | ${gate} | ${page} |`);
  }
  lines.push("");

  for (const p of index.positions) {
    if (p.record === null) continue;
    const { record } = records.get(p.id);
    lines.push(`## ${p.id}. ${record.title_zh}`);
    lines.push("");
    lines.push(`\`${record.slug}\` · ${LABEL[p.derived.lifecycle]} · 紀錄 \`${p.record}\``);
    lines.push("");
    lines.push(record.summary_zh);
    lines.push("");
    lines.push("| 階段 | 適用性 | 狀態 |");
    lines.push("|---|---|---|");
    for (const stage of record.stages) {
      lines.push(`| \`${stage.stage}\` | ${stage.applicability} | ${stage.state} |`);
    }
    lines.push("");
    if (record.work_items.length > 0) {
      lines.push("**實際做過的工作項目**（變動長度，不是固定格）：");
      lines.push("");
      for (const item of record.work_items) {
        lines.push(`- \`${item.key}\` ${item.title} — ${item.state}`);
      }
      lines.push("");
    }
    if (record.demonstrates.length > 0) {
      lines.push("**這個產品量出來的東西：**");
      lines.push("");
      for (const item of record.demonstrates) lines.push(`- ${item}`);
      lines.push("");
    }
    if (record.measured !== null && record.measured !== undefined) {
      const m = record.measured;
      lines.push("```text");
      lines.push(`測試              ${m.tests} 條，${m.test_failures} 條失敗`);
      lines.push(`鑽孔              ${m.drills} 支，${m.drill_mutations_surviving} 個變異活下來`);
      lines.push(`驗收 ID           ${m.acceptance_ids} 條，${m.acceptance_ids_open} 條未結`);
      lines.push(`外包進樹的單元    ${m.outsourced_units_in_tree} 個`
        + `${m.outsourced_units_byte_identical ? "，逐位元未改" : ""}`);
      lines.push("```");
      lines.push("");
    }
    if (p.close !== null) {
      lines.push("```text");
      lines.push(`commit  ${p.close.commit}`);
      lines.push(`tree    ${p.close.tree}`);
      lines.push(`結案    ${p.close.date}`);
      lines.push("```");
      lines.push("");
    }
    lines.push(`席位：建置 ${record.owners.build} · manifest/oracle `
      + `${record.owners.manifest_and_oracle} · 系統驗收 ${record.owners.system_acceptance}`);
    lines.push("");
  }
  return lines.join("\n");
}

if (process.argv[1] !== undefined && process.argv[1].endsWith("render-index.mjs")) {
  const records = loadRecords();
  const index = buildIndex(records);
  writeFileSync(path.join(here, "index.json"),
    JSON.stringify(index, null, 2) + "\n", "utf8");
  writeFileSync(path.join(here, "README.md"), renderReadme(index, records), "utf8");
  process.stdout.write("  wrote portfolio/index.json and portfolio/README.md\n");
}
